### ISSUE TITLE
DLC key error

### ISSUE THREAD

**Issue by TheJa937** [olescheller/anno1800-retroactive-dlc-activation#4]
I have an Anno 1800 save which has no DLC loaded into it. When I try to use the GUI version I get the following error:
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "a1800da\gui.py", line 45, in apply_changes
  File "a1800da\lib.py", line 285, in insert_dlcs
  File "a1800da\lib.py", line 299, in insert_dlc
KeyError: 'DLC'

after printing out the contents of self.game_setup_reader.attribute_node_to_id (located in line 299) and comparing it to the content of a different Anno save which did have a DLC I found the following:

DLC: {'id': 32776, 'PeerCount': 32769, 'count': 32770, 'CompanyName': 32771, 'AccountId': 32772, 'CompanyPortraitGuid': 32773, 'CompanyLogoGuid': 32774, 'Asset': 32775, 'Coop': 32777, 'PlayerPossessions': 32778, 'GameSeed': 32779, 'Customizable': 32780, 'SavegameFolderW': 32781, 'DLC': 32782, 'ActiveHappyDayEvents': 32783, 'Profile': 32784}

No DLC:  {'id': 32776, 'PeerCount': 32769, 'count': 32770, 'CompanyName': 32771, 'AccountId': 32772, 'CompanyPortraitGuid': 32773, 'CompanyLogoGuid': 32774, 'Asset': 32775, 'Coop': 32777, 'PlayerPossessions': 32778, 'GameSeed': 32779, 'Customizable': 32780, 'SavegameFolderW': 32781, 'ActiveHappyDayEvents': 32782, 'Profile': 32783}

The DLC pointer seems to be missing. Is there any way to open the file manually and insert the missing DLC flag? I wasn't able to make out the content of the .a7s file on my own.

**Comment by olescheller** [comment]
Hi! Currently the save game must have at least one DLC active for the script to work, unfortunately. 

As you mentioned, a save game without DLCs is missing some essential tags, which are currently used to insert the DLCs manually.  Adding those new tags to the file is more complicated than just adding "tag instances". All tags are listed in a schema description at the end of the file, which requires some additional and different effort to extend. I haven't had the time to program that part out, since I also didn't need it for myself 🫣. I might come back to it at some point, but have no plans in the near future 😐

**Comment by Halavus** [comment]
Hi, thanks for your answer on #5 . The save I tried had DLCs active.

**Comment by ln8711** [comment]
Please try this if any one still got the issue
https://github.com/BoSoeborgPetersen/anno1800-retroactive-dlc-activation

**Comment by adamsumme107** [comment]
Could I fix this issue by buying another DLC, activating it in my saved game to create those tags and then activate another DLC using your GUI application?

**Comment by classiphil** [comment]
I absolutely think so, although I can not try it out, because I already have all the DLC activated.
